import type { Course, Instructor } from '@/lib/types';

export const instructors: Instructor[] = [
  {
    id: '1',
    name: 'Dr. Evelyn Reed',
    bio: 'An award-winning developer and educator with 15 years of experience in web technologies. Evelyn is passionate about making coding accessible to everyone.',
    expertise: ['React', 'Next.js', 'TypeScript', 'Web Performance'],
    avatarId: 'instructor-1',
    email: 'evelyn.reed@coursemaestro.com',
  },
  {
    id: '2',
    name: 'Marcus Chen',
    bio: 'Marcus is a UX/UI design lead at a top tech company. He enjoys mentoring new designers and believes in a user-first approach to product design.',
    expertise: ['UI/UX Design', 'Figma', 'User Research', 'Design Systems'],
    avatarId: 'instructor-2',
    email: 'marcus.chen@coursemaestro.com',
  },
  {
    id: '3',
    name: 'Aisha Khan',
    bio: 'Aisha is a data scientist and analyst who has worked with several Fortune 500 companies, helping them make data-driven decisions. She loves teaching and simplifying complex topics.',
    expertise: ['Python', 'Data Science', 'Machine Learning', 'SQL'],
    avatarId: 'instructor-3',
    email: 'aisha.khan@coursemaestro.com',
  },
];

export const courses: Course[] = [
  {
    id: '1',
    title: 'Advanced Web Development with Next.js',
    description: 'Master server-side rendering, static site generation, and more with Next.js.',
    longDescription: 'Dive deep into the architecture and features of Next.js. This course covers everything from basic setup to advanced topics like Server Components, Server Actions, and deploying your application to production. You will build a full-stack application from scratch.',
    instructorId: '1',
    category: 'Web Development',
    learningObjectives: [
      'Build full-stack applications with Next.js',
      'Understand and implement Server and Client Components',
      'Optimize for performance and SEO',
      'Deploy Next.js applications with confidence',
    ],
    syllabus: [
      { week: 1, topic: 'Introduction to Next.js', content: 'Setting up your environment, pages, and routing.' },
      { week: 2, topic: 'App Router and Layouts', content: 'Exploring the new App Router, nested layouts, and route groups.' },
      { week: 3, topic: 'Data Fetching', content: 'Server-side data fetching, ISR, and SWR.' },
      { week: 4, topic: 'Advanced Features', content: 'Server Actions, middleware, and API routes.' },
    ],
    materials: ['Course videos', 'Code repositories', 'Final project specifications'],
    imageId: 'course-1',
    duration: '8 Weeks',
    level: 'Intermediate',
  },
  {
    id: '2',
    title: 'UI/UX Design Fundamentals',
    description: 'Learn the principles of creating beautiful and user-friendly interfaces.',
    longDescription: 'This course provides a comprehensive introduction to the world of UI/UX design. You will learn about user research, wireframing, prototyping, and visual design principles. By the end, you\'ll have a portfolio-ready project.',
    instructorId: '2',
    category: 'Design',
    learningObjectives: [
      'Conduct user research and create personas',
      'Design wireframes and high-fidelity mockups',
      'Prototype and test your designs',
      'Build a design portfolio',
    ],
    syllabus: [
      { week: 1, topic: 'The Design Process', content: 'Understanding the stages of product design.' },
      { week: 2, topic: 'User Research', content: 'Methods for understanding user needs.' },
      { week: 3, topic: 'Wireframing & Prototyping', content: 'Using Figma to create interactive prototypes.' },
      { week: 4, topic: 'Visual Design', content: 'Color theory, typography, and layout.' },
    ],
    materials: ['Figma templates', 'Reading materials', 'Case study guidelines'],
    imageId: 'course-2',
    duration: '6 Weeks',
    level: 'Beginner',
  },
  {
    id: '3',
    title: 'Data Science with Python',
    description: 'Unlock insights from data using Python, Pandas, and Matplotlib.',
    longDescription: 'Get started with one of the most in-demand fields. This course teaches you the fundamentals of data analysis and visualization using Python. You will work with real-world datasets to answer business questions.',
    instructorId: '3',
    category: 'Data Science',
    learningObjectives: [
      'Manipulate data with Pandas',
      'Create visualizations with Matplotlib and Seaborn',
      'Understand statistical concepts for data analysis',
      'Complete an end-to-end data analysis project',
    ],
    syllabus: [
      { week: 1, topic: 'Python for Data Science', content: 'NumPy and Pandas basics.' },
      { week: 2, topic: 'Data Wrangling', content: 'Cleaning and preparing messy data.' },
      { week: 3, topic: 'Data Visualization', content: 'Plotting with Matplotlib and Seaborn.' },
      { week: 4, topic: 'Case Study', content: 'Applying your skills to a real dataset.' },
    ],
    materials: ['Jupyter Notebooks', 'Datasets', 'Cheatsheets'],
    imageId: 'course-3',
    duration: '4 Weeks',
    level: 'Beginner',
  },
  {
    id: '4',
    title: 'Agile Project Management',
    description: 'Learn to manage projects efficiently with Agile and Scrum methodologies.',
    longDescription: 'In today\'s fast-paced environment, Agile is a critical skill. This course teaches the principles of Agile development, the Scrum framework, and how to lead high-performing teams. You\'ll learn to manage backlogs, plan sprints, and run effective meetings.',
    instructorId: '1',
    category: 'Business',
    learningObjectives: [
      'Understand the Agile manifesto and principles',
      'Master the Scrum framework roles, events, and artifacts',
      'Learn to use popular Agile tools like Jira',
      'Prepare for Scrum Master certification',
    ],
    syllabus: [
        { week: 1, topic: 'Intro to Agile', content: 'Agile vs. Waterfall.' },
        { week: 2, topic: 'Scrum Deep Dive', content: 'Roles, events, and artifacts.' },
        { week: 3, topic: 'Kanban and Lean', content: 'Visualizing workflow and limiting WIP.' },
        { week: 4, topic: 'Scaling Agile', content: 'Frameworks like SAFe and LeSS.' },
    ],
    materials: ['Templates', 'Case studies', 'Certification prep questions'],
    imageId: 'course-4',
    duration: '4 Weeks',
    level: 'Intermediate',
  },
  {
    id: '5',
    title: 'Digital Marketing Mastery',
    description: 'Grow your business with SEO, social media, and content marketing.',
    longDescription: 'This comprehensive course covers all essential channels of digital marketing. From search engine optimization (SEO) to social media strategy and email marketing, you will learn how to create and execute a holistic digital marketing plan.',
    instructorId: '2',
    category: 'Marketing',
    learningObjectives: [
      'Develop a digital marketing strategy',
      'Optimize websites for search engines (SEO)',
      'Create and manage social media campaigns',
      'Analyze marketing performance using analytics tools',
    ],
    syllabus: [
        { week: 1, topic: 'Marketing Strategy', content: 'Defining goals and KPIs.' },
        { week: 2, topic: 'SEO and Content', content: 'Keyword research and on-page optimization.' },
        { week: 3, topic: 'Paid Advertising', content: 'Google Ads and social media ads.' },
        { week: 4, topic: 'Analytics', content: 'Measuring success with Google Analytics.' },
    ],
    materials: ['Checklists', 'Tool recommendations', 'Live campaign examples'],
    imageId: 'course-5',
    duration: '8 Weeks',
    level: 'Beginner',
  },
  {
    id: '6',
    title: 'Photography for Beginners',
    description: 'Learn to take stunning photos by mastering your camera\'s manual settings.',
    longDescription: 'Move beyond auto mode and take creative control of your camera. This course covers the fundamentals of exposure, composition, and lighting. You\'ll learn how to use aperture, shutter speed, and ISO to capture the photos you envision.',
    instructorId: '3',
    category: 'Creative',
    learningObjectives: [
      'Understand the exposure triangle (Aperture, Shutter Speed, ISO)',
      'Apply composition rules to create more compelling images',
      'Learn about different types of light and how to use them',
      'Edit your photos for a professional look',
    ],
    syllabus: [
        { week: 1, topic: 'Your Camera', content: 'Understanding modes and settings.' },
        { week: 2, topic: 'Exposure', content: 'Mastering aperture, shutter speed, and ISO.' },
        { week: 3, topic: 'Composition', content: 'Rules of thirds, leading lines, and framing.' },
        { week: 4, topic: 'Editing', content: 'Introduction to Lightroom and basic adjustments.' },
    ],
    materials: ['Weekly photo assignments', 'Editing presets', 'Gear guide'],
    imageId: 'course-6',
    duration: '4 Weeks',
    level: 'Beginner',
  },
];
